### ISSUE TITLE
empty page triggers error

### ISSUE THREAD

**Issue by JohnMica** [trilbymedia/grav-plugin-image-captions#1]
hi guys,

it seems that an empty page (while this plugin is enabled) will trigger an error

all referenced in this error #1771

**Comment by JohnMica** [comment]
#https://github.com/getgrav/grav/issues/1771

**Comment by PadineanuCosmin** [comment]
Hi,

Since modular pages actually are empty the plugin breaks these pages.
Any estimated release date for a version with this bugfix?

Thanks.

**Comment by foufrix** [comment]
Same here where i use only a twig template with no page content

**Comment by paulhibbitts** [comment]
I've run across this issue too, as well as causing Search Results to throw an error. Looks like a PR has been submitted to fix the issue (I've downloaded the Develop branch and the empty page issue looks solved) https://github.com/trilbymedia/grav-plugin-image-captions/pull/7 Any chance for a new release soon @rhukster ? Thanks very much!

**Comment by rhukster** [comment]
Ill try to take a look at this today.

**Comment by paulhibbitts** [comment]
Awesome, thanks so much @rhukster ! I've just updated the plugin in an install and it works great👍
