### ISSUE TITLE
Bug with grav-plugin-image-captions

### ISSUE THREAD

**Issue by mkacfr** [trilbymedia/grav-plugin-image-captions#13]
For me, the grav-plugin-image-captions created a server error --> https://ibb.co/T47vMnv

Thanks GRAVTEAM for your wonderfull work and updates... Amazing !!!

Take Care,
-Michael- (from France)

**Comment by rhukster** [comment]
I've released v2.0.1 that has an updated version of the DiDom library.  Please let me know if this resolves your issue.  Cheers.
