### ISSUE TITLE
Linking image to plugin through class attribute breaks page

### ISSUE THREAD

**Issue by MaLoSch** [trilbymedia/grav-plugin-image-captions#16]
Hi!

I'm building a page template in my own theme and trying to use the image captions plugin. Add `![My Title](image.jpg?classes=caption "My Caption")` to the page through the admin panel, results in the following error:

**'This site can’t be reached. The connection was reset.'**

Detaching the image from the plugin by using a different class name for the image than defined in the plugin scope loads the page just fine. It just breaks as soon as the plugin scope matches with the image HTML output.

I checked if anyone reported a similar issue but couldn't find anything. I didn't change any plugin settings and I am using Grav v1.6.23 - Admin v1.9.13 - Image Captions  v2.0.1.

**Comment by rhukster** [comment]
Could never replicate this.
