### ISSUE TITLE
Scan the entire page feature removes ending tags from elements

### ISSUE THREAD

**Issue by replayshot** [trilbymedia/grav-plugin-image-captions#17]
When the Scan the entire page feature is enabled, it removes ending / or closing tags from certain elements as well as from the actual <img that is being wrapped with the captions.

This would not be a problem since the closing "/" is mainly deprecated now, however, it causes an issue with the RSS output with plugin: https://github.com/getgrav/grav-plugin-feed - it removes all `</link>` elements from the RSS which causes it to be malformed and not functional.

**Comment by rhukster** [comment]
I think i know the issue.. we are using DiDom to parse the page and that is defaulting to TYPE_HTML, but for RSS feeds it would need to use TYPE_XML.  We need to do some more advanced logic to determine if the extension you are requesting is an XML type (RSS, etc), or an HTML type.  Kinda busy right now so can't get to this right now.  

If you want to attempt to fix it yourself, check out line 110 of `image-captions.php`, and you will need to add the logic for the type based on their docs: https://github.com/Imangazaliev/DiDOM#creating-new-document

**Comment by replayshot** [comment]
thanks for the response. No stress, since it is possible to work around it by disabling the Scan the entire page setting, it is not that crucial imho. I am afraid, my coding skills are not the best, so it is better a more experienced programmer makes the fix.
