### ISSUE TITLE
Image caption is part of lightbox when used with Featherlight Grav plugin

### ISSUE THREAD

**Issue by vecjh** [trilbymedia/grav-plugin-image-captions#19]
Hello, I have your plugin running along with Featherlight Grav plugin. When both are applied to the image then image caption becomes part of the lightbox: it appears like a hyperlink with hyperlink css. Is it possible to separate image caption from lightbox? I.e. for caption to appear as if there was no Grav lightbox action.

example usage: `![](image-1.jpg?classes=center,caption&lightbox&resize=400 "my image caption")`

**Comment by rhukster** [comment]
Unfortunately not with this plugin. You could use shortcode-core plugin and use the `[figure]` shortcode (https://github.com/getgrav/grav-plugin-shortcode-core#figure) and it should work.

**Comment by vecjh** [comment]
thanks, got it.
