### ISSUE TITLE
generates <figure>...</figure> inside of <p>...</p> - invalid HTML

### ISSUE THREAD

**Issue by pgr1973** [trilbymedia/grav-plugin-image-captions#8]
When the images are rendered inside of paragraphs, this plugins leaves the paragraphs and replaces the `<img ...` or `<a ...><img ...` with the newly built `<figure ...`.

That results in `<figure>` inside of `<p>` which is invalid html (https://validator.w3.org).

**Comment by rhukster** [comment]
something to look into...
