### ISSUE TITLE
Plugin add incorrect second <html><body> tags

### ISSUE THREAD

**Issue by vectortarget** [trilbymedia/grav-plugin-image-captions#9]
Hi
I use "Quark" Grav theme. Plugin "image captions" add incorrect second <html><body> tags at the start of page "content" (text of arcicle for example) and the end of this. I am sure that it is bug of "image captions" plugin. I turned it OFF and this problem disappeared, then turned it ON and problem appear again. You can check it in source-code on my blog page for example https://vectortarget.ru/blog/nakrutka-podpischikov-vkontakte-pochemu-eto-ne-prineset-pribyli
![git](https://user-images.githubusercontent.com/39743742/40679306-7cbdc0e0-638b-11e8-9ee8-a71608b72a2a.PNG)

**Comment by rhukster** [comment]
Hmm. definitely an issue there.
